### ISSUE TITLE
Concat issue

### ISSUE THREAD

**Issue by jadestorm** [voxpupuli/puppet-keepalived#106]
Hi there!  Not necessarily an issue so much as a "warning".  I had concat 2.1.0 installed and "randomly" every puppet run the ordering of my 2 hiera-based VRRP instances were swapping.  concat 2.2.0 actually fixes this behavior, so FYI in case it comes up!

**Comment by Dan33l** [comment]
Hi @jadestorm .
The module is migrated to Vox Pupuli.
Are you yet a user of the module ? Can you produce a PR to fix this ?

**Comment by Dan33l** [comment]
PR #160 version updated.

**Comment by jadestorm** [comment]
I am still using the module =)  But looks like the issue got resolved via PR 160 so let me know if you still need me to do something!  Thanks!  (hopefully this comment doesn't reopen the issue)
