### ISSUE TITLE
forge version of module vs current master - vrrp script timeouts

### ISSUE THREAD

**Issue by liqw33d** [voxpupuli/puppet-keepalived#111]
the latest version of module distributed as 1.2.4 at puppet forge does **not** contain following commit:
https://github.com/arioch/puppet-keepalived/commit/c64654d1ce85383008d81f7a398e9002bbe0ad72
.. that means setting timeout for scripts isn't available.
please do new release with this feature, so module can be installed from puppet forge.
thanks

**Comment by Dan33l** [comment]
Hi @liqw33d .
The module in now migrated to Voxpupuli. We will produce a release 2.0.0 under our name space on the forge.

**Comment by saz** [comment]
As there is release 2.1.0 on the forge, I think this issue can be closed.
