### ISSUE TITLE
vrrp_isntances configs

### ISSUE THREAD

**Issue by cjtoolseram** [voxpupuli/puppet-keepalived#118]
advert_int
garp_master_delay

With this 2 configs, can we make them optional not to appear int he keepalived.conf?

also with the vip config:

```
  virtual_ipaddress {
    23.24.25.26  dev eth1
  }
```

Can we make the `dev` and `eth1` optional too from the templates?

please advise

**Comment by saz** [comment]
+1 for making `dev eth1` optional, e.g if `use_vmac` is set. Anything else will result in the wrong interface.

**Comment by sprd-bena** [comment]
Regarding `dev` and `use_vmac`: I think this was resolved with https://github.com/voxpupuli/puppet-keepalived/commit/a324c7bb#diff-87675708e3ca7c1b55dad9128dbfabcbe61466ea8952499670fe4af11f40f7c1R153-R154

**Comment by igalic** [comment]
solved in #186
