### ISSUE TITLE
forge version 1.2.5 is outdated

### ISSUE THREAD

**Issue by khaefeli** [voxpupuli/puppet-keepalived#131]
the version 1.2.5 on the puppet forge is missing some nice features like the following commit: https://github.com/arioch/puppet-keepalived/commit/8ee0cf84a69646732c3f0a30c60a22fa970109be

this is needed to avoid the loop if the `ip_vs` module isn't loaded: 
> Keepalived_healthcheckers[1689]: IPVS: Can't initialize ipvs: Protocol not available

`sysconf_options => '-vrrp',`

**Comment by khaefeli** [comment]
@arioch looks like the module isn't maintained anymore. Could you handover it to the community / https://github.com/voxpupuli/ ?

**Comment by alexjfisher** [comment]
1.3.0 was released last year.  Expect a 2.0.0 vox pupuli release some time soon.
