### ISSUE TITLE
Fix wrong warning

### ISSUE THREAD

**Issue by sts** [voxpupuli/puppet-keepalived#141]
Please fix the warning returned by fail when checking `keepalived::vrrp::instance` parameters. It expects a String and asks for an Integer. 

If you pass an Integer instead of a String to the defined type for either `$priority` or `$virtual_router_id` it will fail and ask to pass an Integer instead! This is quite confusing and took me quite some time to figure out! 🙄

https://github.com/arioch/puppet-keepalived/blob/master/manifests/vrrp/instance.pp#L182
https://github.com/arioch/puppet-keepalived/blob/master/manifests/vrrp/instance.pp#L185

Alternatively fix the check and actually expect an integer. Also IMHO it doesn't make a difference in the current implementation whether its a String or an Integer as both will be rendered fine to the actual configuration file.

**Comment by jfleury-at-ovh** [comment]
Also, `virtual_router_id` is limited to the range [1, 255] while the doc state it can be in the range [0, 255]:

```
# arbitrary unique number from 0 to 255
# used to differentiate multiple instances of vrrpd
# running on the same NIC (and hence same socket).
virtual_router_id 51
```

**Comment by Dan33l** [comment]
hi @sts and @jfleury-at-ovh thank you for reporting.
The module migrated to Vox Pupuli.
If it is accurate with the current code, can you propose a PR to fix this  ?

**Comment by sts** [comment]
This was already fixed by https://github.com/voxpupuli/puppet-keepalived/commit/5ce7c9e14e3993765908f1fa062c3dbc0c9fcc84#diff-6ad530b3cfcd82a8544d33bb9dfe3f4aR144
