### ISSUE TITLE
Add Ubuntu to Metadata

### ISSUE THREAD

**Issue by nabber00** [voxpupuli/puppet-keepalived#175]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: All
- Ruby: All
- Distribution: Ubuntu
- Module version: 2.0.0

## What are you seeing
metadata.json does not include any Ubuntu versions.  I am requesting that recent versions be added.

## What behaviour did you expect instead
I believe the module is already compatible with Ubuntu since it falls under the "osfamily" fact of Debian which is already implemented.  I have tested on 16.04 and 18.04 without issue.

**Comment by ekohl** [comment]
Would you be willing to work on a patch? Ideally also adding acceptance tests since that's the best way to prove it works and doesn't regress.
