### ISSUE TITLE
support of additional parameters

### ISSUE THREAD

**Issue by a-dekker** [voxpupuli/puppet-keepalived#205]
I noticed` vrrp_garp_lower_prio_repeat` and `vrrp_higher_prio_send_advert` are now supported as parameters. But I also would like to configure the parameters `vrrp_garp_master_refresh` and `vrrp_garp_lower_prio_delay`.
Could you add those parameters as well? Adding an option to provide custom key-values would also be an alternative.

**Comment by bastelfreak** [comment]
@a-dekker can you provide a PR for this?

**Comment by a-dekker** [comment]
I could give it a try. But what's your preference: adding this specific two parameters, or add an option to pass custom key-values?

**Comment by bastelfreak** [comment]
having dedicated parameters is nice, because that allows us to enforce a very specific datatype, so I would go with that.

**Comment by a-dekker** [comment]
Created PR https://github.com/voxpupuli/puppet-keepalived/pull/206
