### ISSUE TITLE
vrrp_script init_fail parameter

### ISSUE THREAD

**Issue by ggoas-interop** [voxpupuli/puppet-keepalived#257]
Hello,

The `keepalived::vrrp::script` class does not support the "init_fail" parameter. Per the [keepalived ChangeLog](https://github.com/acassen/keepalived/blob/master/ChangeLog#L4310), the "init_fail" parameter has been available since the 1.3.2 release of keepalived. Can support for the parameter please be added?

Thanks!

**Comment by root-expert** [comment]
Hello @ggoas-interop! Are you able to provide a PR with tests adding this feature?
