### ISSUE TITLE
puppetlabs-concat vesrion

### ISSUE THREAD

**Issue by sandwitch** [voxpupuli/puppet-keepalived#301]
,
Is it possible to bump the puppetlabs-concat version to 9.0.0? Should i create a pull request?

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

**Comment by kenyon** [comment]
Yes, create a pull request.

**Comment by sandwitch** [comment]
since master is at @3.6.1-rc0 and both stdlib and concat have < 10.0.0 as maximum version I think we can close this issue?
