### ISSUE TITLE
Sensitive Data

### ISSUE THREAD

**Issue by cocker-cc** [voxpupuli/puppet-keepalived#338]
To not reveal sensitive Data
* either wrap the rendered Template in `manifests/vrrp/instance.pp`, like
  ```puppet
  concat::fragment { "keepalived.conf_vrrp_instance_${_name}":
    target  => "${keepalived::config_dir}/keepalived.conf",
    content => Sensitive(template('keepalived/vrrp_instance.erb')),
    order   => "100-${_ordersafe}-000",
  }
  ```
  (`concat` handles sensitive Data since `7.4.0`)
* or use EPP instead of ERB, as EPP does handle sensitive Data natively

**Comment by kenyon** [comment]
Do you want to make a pull request that adds this to the module's documentation?
